Tests for Phoenix Payoff
riskfuel/autocall-monte-carlo pull request #11
Opened 2021-11-29 19:43 UTC by RiskFuelDmitry

2021-12-01 15:01 UTC, artcoding requested changes

2021-12-01 15:01 UTC, artcoding commented on lib/src/payoff.rs
> +        assert_eq!(payoff.coupon(0.9), 1.04);
Add tests for returns above 1.0. E.g. 1.01 and 1.06. The last one will exceed the autocall level.

2021-12-01 15:03 UTC, RiskFuelDmitry commented on lib/src/payoff.rs
> +    fn test_phoenix_new(){
The constructor initialises variables correctly if there is some business logic when we create Payoff from Trade.

2021-12-02 16:42 UTC, RiskFuelDmitry commented on lib/src/payoff.rs
> +    fn test_phoenix_new(){
This test checks that the Payoff fields are populated correctly when an object is created from the Trade created based on a JSON file.

2021-12-02 17:35 UTC, artcoding approved these changes

2021-12-02 18:14 UTC, merged